version: '3.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/srv/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testblogapi
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005"
    tty: true 
    depends_on:
      - postgres
      - redis
volumes:
  pgdata:
